services:
  postgres-db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: "bookmarks"
      POSTGRES_PASSWORD: "bookmarks_admin"
      POSTGRES_DB: "bookmarks_pg"
    ports:
      - "5432:5432"

  django:
    container_name: django_app
    image: django_app
    build:
      context: ./BMs
    ports:
      - "8001:8000"
    env_file:
      - conf/.env
    volumes:
      - static-files:/app/static
      - media-files:/app/media
      - ./BMs/BMs/settings.py:/app/BMs/settings.py
    depends_on:
      - postgres-db
      - redis

  web-server:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static-files:/static
      - media-files:/media
    depends_on:
      - django

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  static-files:
  media-files:
